# First command to check for object code updates and then run linker to run code
p1: Student.o HtmlStudentTable.o project1.o
		g++  --stdc++11 project1.cpp Student.cpp HtmlStudentTable.cpp


# p1: Student.o HtmlStudentTable.o project1.o
# 		g++ -o  --stdc++11 Project_1 Student.cpp HtmlStudentTable.cpp project1.cpp

# This removes the object codes if they been updated
clean: Student.o HtmlStudentTable.o project1.o
		rm Student.o HtmlStudentTable.o project1.o


